- name: copy to destination 
  hosts: servera.lab.example.com
  become: true
  tasks:
    - name: copy content  in a file which doesn't exists
      copy:
        content : "this is file for copy content via ansible playbook"
        dest: /home/student/exam364.txt
