---
- name: Restart OpenShift Pod
  hosts: localhost
  gather_facts: no

  vars:
    openshift_project_name: dheeraj-joria-dev
    pod_name: mypod

  tasks:
    - name: Log in to OpenShift
      command: > 
        oc login --token=sha256~4vaigqmSV6BzWt8SULtHJBWsL7FJNC-xBsPpldGAea8 --server=https://api.rm1.0a51.p1.openshiftapps.com:6443
        

    - name: Switch to the target OpenShift project
      command: oc project {{ openshift_project_name }}

    - name: Restart the pod by deleting it
      command: oc delete pod {{ pod_name }}

    - name: Wait for pod to be recreated and running
      shell: |
        oc get pods -n {{ openshift_project_name }} --no-headers | grep {{ pod_name }} | grep Running
      register: pod_status
      retries: 10
      delay: 10
      until: pod_status.rc == 0
